import 'package:flutter/material.dart';
import 'package:school_system/core/helper/shared_prefs_helper.dart';

class LocalizationHelper {
  static final ValueNotifier<Locale> localeNotifier = ValueNotifier<Locale>(
    Locale(SharedPrefsHelper.languageCode),
  );

  static Locale get currentLocale => localeNotifier.value;

  static bool get isArabic => currentLocale.languageCode == 'ar';

  static void setLanguage(String langCode) {
    SharedPrefsHelper.setLanguageCode(langCode);
    localeNotifier.value = Locale(langCode);
  }

  static String tr(String key) {
    final lang = currentLocale.languageCode;
    return _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      // General & Common
      'app_title': 'School System',
      'back': 'Back',
      'save': 'Save',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'success': 'Success',
      'error': 'Error',
      'loading': 'Loading...',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Log Out',
      'logout_confirm': 'Are you sure you want to log out?',
      'yes': 'Yes',
      'no': 'No',
      'view_all': 'View All',
      'days_mon': 'Mon',
      'days_tue': 'Tue',
      'days_wed': 'Wed',
      'days_thu': 'Thu',
      'days_fri': 'Fri',
      'days_sat': 'Sat',
      'days_sun': 'Sun',
      'nav_home': 'Home',
      'nav_classes': 'Classes',
      'nav_messages': 'Messages',
      'nav_alerts': 'Alerts',
      'nav_profile': 'Profile',
      'nav_my_kids': 'My Kids',
      'nav_payments': 'Payments',
      'nav_subjects': 'Subjects',
      'smart_tutor_title': 'Smart Tutor AI',
      'smart_tutor_subtitle': 'Personalized help available',

      // Onboarding
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'onboarding_title_1': 'Manage school activities easily',
      'onboarding_desc_1':
          'Organize your classes, schedules, and student activities in one place.',
      'onboarding_title_2': 'Track attendance and grades',
      'onboarding_desc_2':
          'Monitor student performance with real-time analytics and detailed progress reports at your fingertips.',
      'onboarding_title_3': 'Learn smarter with SmartTutor AI',
      'onboarding_desc_3':
          'Experience the power of personalized learning guided by advanced artificial intelligence designed to adapt to your unique pace.',

      // Auth
      'select_role': 'Select Your Role',
      'select_role_desc': 'Choose your role to log in to the school portal',
      'teacher': 'Teacher',
      'student': 'Student',
      'parent': 'Parent',
      'teacher_desc':
          'Manage your classes, track student progress, and share learning resources effortlessly with your students.',
      'student_desc':
          'Access your assignments, join interactive live classes, and visualize your personal learning journey.',
      'parent_desc':
          'Stay updated with your child\'s academic performance, daily attendance, and school-wide announcements.',
      'need_help': 'Need help? ',
      'contact_support': 'Contact Support',
      'welcome_back': 'Welcome Back',
      'login_subtitle': 'Please log in to your account',
      'email': 'Email Address',
      'password': 'Password',
      'remember_me': 'Remember Me',
      'forgot_password': 'Forgot Password?',
      'login_btn': 'Log In',
      'forgot_password_title': 'Forgot Password',
      'forgot_password_subtitle':
          'Enter your registered email address and we\'ll send you a 4-digit code to reset your password.',
      'send_code': 'Send Code',
      'back_to_login': 'Back to login',
      'verification_title': 'Verification Code',
      'verification_subtitle':
          'Enter the 4-digit verification code sent to your email',
      'resend_code': 'Resend Code',
      'verify_and_proceed': 'Verify & Proceed',
      'reset_password_title': 'Reset Password',
      'reset_password_subtitle':
          'Set your new password below. Ensure it is strong and secure.',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'password_req_title': 'Password Requirements',
      'password_req_1': 'At least 8 characters long',
      'password_req_2': 'Must contain an uppercase letter',
      'password_req_3': 'Must contain a number or symbol',
      'success_msg': 'Your password has been changed successfully!',
      'go_to_login': 'Go to Login',

      // Settings
      'notifications_header': 'NOTIFICATIONS',
      'push_notifications': 'Push Notifications',
      'email_alerts': 'Email Alerts',
      'preferences_header': 'PREFERENCES',
      'dark_mode': 'Dark Mode',
      'language_selection': 'Language Selection',
      'language_subtitle': 'English / Arabic',
      'more_header': 'MORE',
      'terms_of_service': 'Terms of Service',
      'help_support': 'Help & Support',
      'select_language': 'Select Language',
      'english': 'English',
      'arabic': 'Arabic',

      // Teacher Role
      'teacher_dashboard': 'Teacher Dashboard',
      'active_classes': 'Active Classes',
      'today_lessons': 'Today\'s Lessons',
      'view_schedule': 'View Schedule',
      'take_attendance': 'Take Attendance',
      'add_new_lesson': 'Add New Lesson',
      'add_new_exam': 'Add New Exam',
      'add_homework': 'Add Homework',
      'attendance_report': 'Attendance Report',
      'weekly_schedule': 'Weekly Schedule',
      'class_students': 'Class Students',
      'present': 'Present',
      'absent': 'Absent',
      'excused': 'Excused',
      'attendance_saved': 'Attendance saved successfully',
      'attendance_method': 'Attendance Method',
      'choose_method': 'Choose how you want to record attendance:',
      'manual_method': 'Manual Checklist',
      'manual_method_desc': 'Mark each student manually',
      'qr_method': 'Dynamic QR Code',
      'qr_method_desc': 'Students scan QR code using their phones',
      'code_method': 'Entry Code',
      'code_method_desc': 'Students enter a 4-digit code on their phones',
      'generate_qr_btn': 'Generate QR Code',
      'entry_code_title': 'Entry Code',
      'lesson_details': 'Lesson Details',
      'exam_details': 'Exam Details',
      'homework_details': 'Homework Details',
      'grade_submission': 'Grade Submission',
      'review_submissions': 'Review Submissions',
      'grade_label': 'Grade',
      'feedback_label': 'Feedback',
      'out_of': 'out of',
      'status_submitted': 'Submitted',
      'status_graded': 'Graded',
      'status_pending': 'Pending',
      'personal_information': 'Personal Information',
      'change_password_title': 'Change Password',
      'current_password': 'Current Password',

      // Student Role
      'student_dashboard': 'Student Dashboard',
      'upcoming_exams': 'Upcoming Exams',
      'pending_homework': 'Pending Homework',
      'my_grades': 'My Grades',
      'subject_details': 'Subject Details',
      'lesson_title': 'Lesson',
      'grades_tab': 'Grades',
      'lessons_tab': 'Lessons',
      'homework_tab': 'Homework',
      'exams_tab': 'Exams',
      'gpa_tracker': 'GPA Tracker',
      'attendance_tracker': 'Attendance Tracker',
      'scan_qr_title': 'Scan Attendance QR',
      'align_qr': 'Align the QR code within the frame to scan',
      'enter_code_title_student': 'Enter Attendance Code',
      'enter_4_digit': 'Enter the 4-digit session code',
      'attendance_success_title': 'Attendance Recorded Successfully!',
      'attendance_success_desc':
          'You have been marked present for this session.',
      'attendance_absent_title': 'You Were Marked Absent',
      'attendance_absent_desc':
          'Please contact your teacher if you believe this is an error.',

      // Parent Role
      'parent_dashboard': 'Parent Dashboard',
      'my_kids': 'My Kids',
      'child_grades': 'Grades & Academic Progress',
      'child_attendance': 'Attendance Status',
      'child_schedule': 'Weekly Class Schedule',
      'payments_header': 'Payments & Tuition',
      'payment_history': 'Payment History',
      'secure_checkout': 'Secure Checkout',
      'pay_now': 'Pay Now',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'receipt': 'Receipt',
      'receipt_no': 'Receipt No',
      'invoice_to': 'Invoice To',
      'payment_method': 'Payment Method',
      'transaction_id': 'Transaction ID',
      'amount': 'Amount',
      'total': 'Total',
      'download_pdf': 'Download PDF',
      'submitted': 'Submitted',
      'due_date': 'Due Date',
      'due_time': 'Due Time',
      'time': 'Time',
      'date': 'Date',
      'description': 'Description',
      'instructions': 'Instructions',
      'reference_files': 'Reference Files',
      'select_class': 'Select Class',
      'choose_class': 'Choose a class',
      'select_subject': 'Select Subject',
      'choose_subject': 'Choose a subject',
      'homework_title': 'Homework Title',
      'homework_title_hint': 'e.g. Quadratic Equations Practice',
      'description_hint': 'Enter a general description of the homework...',
      'instructions_hint': 'Enter specific instructions or requirements...',
      'points_grade': 'Points / Max Grade',
      'attachments': 'Attachments',
      'create_homework': 'Create Homework',
      'fill_required': 'Please fill all required fields',
      'upload_pdf': 'Upload PDF',
      'add_images': 'Add Images',
      'Lesson_title': 'Lesson Title',
      'lesson_title_hint': 'e.g., Introduction to Quadratic Equations',
      'scheduled_date_time': 'Scheduled Date & Time',
      'select_date_time': 'Select date & time',
      'desc_objectives': 'Description/Objectives',
      'learn_hint': 'What will students learn?',
      'publish_lesson': 'Publish Lesson',
      'class_section': 'Class/Section',
      'avg_score': 'AVG SCORE',
      'to_grade': 'TO GRADE',
      'full_name': 'Full Name',
      'email_address': 'Email Address',
      'phone_number': 'Phone Number',
      'department': 'Department',
      'employee_id': 'Employee ID',
      'change_password': 'Change Password',
      'Current_password': 'Current Password',
      'New_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'enrolled': 'ENROLLED',
      'marked_absent': 'MARKED ABSENT',
      'view_class': 'View Class',
      'retry': 'Retry',
      'your_classes_today': 'Your Classes Today',
      'attendance_taken': 'ATTENDANCE TAKEN',
      'without_mark': 'WITHOUT MARK',
      "view_reports": "View Reports",
      "Take_attendance": "Take Attendance",
      "students_count": "{count} Students",
      'students': 'students',
      'View_reports': 'view_report',
      'active_course': 'Active Course', 'schedule': 'Schedule',
      'grading': 'Grading',
      'exam_instructions': 'Exam Instructions',
      'enter_exam_instructions': 'Enter instructions for students...',
      'schedule_exam': 'Schedule Exam',
      'exam_scheduled_successfully': 'Exam scheduled successfully',
      'error_parsing_date': 'Error parsing date/time',
      'file_url_missing': 'File URL is missing',
      'invalid_file_url': 'Invalid file URL',
      'file_downloaded_successfully': 'File downloaded successfully',
      'failed_open_download_file': 'Failed to open/download file',
      'failed_load_exam_details': 'Failed to load exam details.',
      'instructions_students': 'Instructions for Students',
      'reference_materials': 'Reference Materials',
      'pdf_document': 'PDF Document',
      'document': 'Document',
      'date_label': 'DATE',
      'time_label': 'TIME',
      'duration_label': 'DURATION',
      'location_label': 'LOCATION',
      'minutes': 'Minutes',
      'not_available': 'N/A',
      'no_specific_instructions': 'No specific instructions provided.',
    },
    'ar': {
      // General & Common
      'view_reports': 'عرض التقارير',
      'file_url_missing': 'رابط الملف مفقود',
      'invalid_file_url': 'رابط الملف غير صالح',
      'file_downloaded_successfully': 'تم تحميل الملف بنجاح',
      'failed_open_download_file': 'فشل في فتح/تحميل الملف',
      'failed_load_exam_details': 'فشل في تحميل تفاصيل الامتحان',
      'instructions_students': 'تعليمات للطلاب',
      'reference_materials': 'المواد المرجعية',
      'pdf_document': 'ملف PDF',
      'document': 'مستند',
      'date_label': 'التاريخ',
      'time_label': 'الوقت',
      'duration_label': 'المدة',
      'location_label': 'المكان',
      'minutes': 'دقيقة',
      'not_available': 'غير متوفر',
      'no_specific_instructions': 'لا توجد تعليمات محددة.',
      'students': 'طلاب',
      'active_course': 'الكورس الحالي',
      'take_attendance': 'تسجيل الحضور',
      'students_count': '{count} طالب',
      'your_classes_today': 'فصولك اليوم',
      'attendance_taken': 'تم تسجيل الحضور',
      'without_mark': 'بدون تسجيل',
      'app_title': 'النظام المدرسي',
      'schedule': 'الجدول',
      'grading': 'التقييم',
      'exam_instructions': 'تعليمات الامتحان',
      'enter_exam_instructions': 'أدخل تعليمات للطلاب...',
      'schedule_exam': 'جدولة الامتحان',
      'exam_scheduled_successfully': 'تمت جدولة الامتحان بنجاح',
      'error_parsing_date': 'خطأ في قراءة التاريخ/الوقت',
      'back': 'رجوع',
      'save': 'حفظ',
      'submit': 'إرسال',
      'cancel': 'إلغاء',
      'success': 'نجاح',
      'error': 'خطأ',
      'loading': 'جاري التحميل...',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'yes': 'نعم',
      'no': 'لا',
      'view_all': 'عرض الكل',
      'days_mon': 'الإثنين',
      'days_tue': 'الثلاثاء',
      'days_wed': 'الأربعاء',
      'days_thu': 'الخميس',
      'days_fri': 'الجمعة',
      'days_sat': 'السبت',
      'days_sun': 'الأحد',
      'nav_home': 'الرئيسية',
      'nav_classes': 'الفصول',
      'nav_messages': 'الرسائل',
      'nav_alerts': 'التنبيهات',
      'nav_profile': 'الملف الشخصي',
      'nav_my_kids': 'أبنائي',
      'nav_payments': 'المدفوعات',
      'nav_subjects': 'المواد',
      'smart_tutor_title': 'المعلم الذكي AI',
      'smart_tutor_subtitle': 'مساعد شخصي متاح الآن',

      // Onboarding
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'بدء الاستخدام',
      'onboarding_title_1': 'إدارة الأنشطة المدرسية بسهولة',
      'onboarding_desc_1':
          'نظّم فصولك الدراسية، وجداولك، وأنشطة الطلاب في مكان واحد.',
      'onboarding_title_2': 'متابعة الحضور والدرجات',
      'onboarding_desc_2':
          'تابع أداء الطلاب بتحليلات فورية وتقارير تقدم مفصلة بين يديك.',
      'onboarding_title_3': 'تعلم بذكاء أكبر مع معلم الذكاء الاصطناعي',
      'onboarding_desc_3':
          'اختبر قوة التعلم الشخصي الموجه بالذكاء الاصطناعي المتقدم المصمم ليتناسب مع وتيرتك الخاصة.',

      // Auth
      'select_role': 'اختر دورك',
      'select_role_desc': 'اختر دورك لتسجيل الدخول إلى البوابة المدرسية',
      'teacher': 'معلم',
      'student': 'طالب',
      'parent': 'ولي أمر',
      'teacher_desc':
          'أدر فصولك الدراسية، وتابع تقدم طلابك، وشارك المصادر التعليمية بسهولة مع طلابك.',
      'student_desc':
          'احصل على واجباتك، وانضم إلى الفصول التفاعلية المباشرة، وشاهد رحلتك التعليمية الشخصية.',
      'parent_desc':
          'كن على اطلاع دائم بأداء طفلك الأكاديمي، وحضوره اليومي، والإعلانات المدرسية العامة.',
      'need_help': 'هل تحتاج لمساعدة؟ ',
      'contact_support': 'اتصل بالدعم',
      'welcome_back': 'مرحباً بعودتك',
      'login_subtitle': 'الرجاء تسجيل الدخول إلى حسابك',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'remember_me': 'تذكرني',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'login_btn': 'تسجيل الدخول',
      'forgot_password_title': 'هل نسيت كلمة المرور؟',
      'forgot_password_subtitle':
          'أدخل بريدك الإلكتروني المسجل وسنرسل لك رمزاً مكوناً من 4 أرقام لإعادة تعيين كلمة المرور.',
      'send_code': 'إرسال الرمز',
      'back_to_login': 'العودة لتسجيل الدخول',
      'verification_title': 'رمز التحقق',
      'verification_subtitle':
          'أدخل رمز التحقق المكون من 4 أرقام المرسل إلى بريدك الإلكتروني',
      'resend_code': 'إعادة إرسال الرمز',
      'verify_and_proceed': 'التحقق والمتابعة',
      'reset_password_title': 'إعادة تعيين كلمة المرور',
      'reset_password_subtitle':
          'عيّن كلمة المرور الجديدة أدناه. تأكد من أنها قوية وآمنة.',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'password_req_title': 'متطلبات كلمة المرور',
      'password_req_1': '8 أحرف على الأقل',
      'password_req_2': 'يجب أن تحتوي على حرف كبير',
      'password_req_3': 'يجب أن تحتوي على رقم أو رمز',
      'success_msg': 'تم تغيير كلمة المرور بنجاح!',
      'go_to_login': 'الذهاب لتسجيل الدخول',

      // Settings
      'notifications_header': 'الإشعارات',
      'push_notifications': 'إشعارات الهاتف',
      'email_alerts': 'تنبيهات البريد الإلكتروني',
      'preferences_header': 'التفضيلات',
      'dark_mode': 'الوضع الداكن',
      'language_selection': 'اختيار اللغة',
      'language_subtitle': 'العربية / English',
      'more_header': 'المزيد',
      'terms_of_service': 'شروط الخدمة',
      'help_support': 'المساعدة والدعم',
      'select_language': 'اختر اللغة',
      'english': 'English',
      'arabic': 'العربية',

      // Teacher Role
      'teacher_dashboard': 'لوحة المعلم',
      'active_classes': 'الفصول النشطة',
      'today_lessons': 'دروس اليوم',
      'view_schedule': 'عرض الجدول',
      'Take_attendance': 'تسجيل الحضور',
      'add_new_lesson': 'إضافة درس جديد',
      'add_new_exam': 'إضافة اختبار جديد',
      'add_homework': 'إضافة واجب منزلي',
      'attendance_report': 'تقرير الحضور',
      'weekly_schedule': 'الجدول الأسبوعي',
      'class_students': 'طلاب الفصل',
      'present': 'حاضر',
      'absent': 'غائب',
      'excused': 'مستأذن',
      'attendance_saved': 'تم حفظ الحضور بنجاح',
      'attendance_method': 'طريقة الحضور',
      'choose_method': 'اختر كيفية تسجيل الحضور:',
      'manual_method': 'قائمة الحضور والغياب',
      'manual_method_desc': 'تسجيل كل طالب يدوياً',
      'qr_method': 'رمز QR ديناميكي',
      'qr_method_desc': 'يمسح الطلاب رمز QR باستخدام هواتفهم',
      'code_method': 'رمز الدخول',
      'code_method_desc': 'يدخل الطلاب رمزاً من 4 أرقام على هواتفهم',
      'generate_qr_btn': 'إنشاء رمز QR',
      'entry_code_title': 'رمز الدخول',
      'lesson_details': 'تفاصيل الدرس',
      'exam_details': 'تفاصيل الاختبار',
      'homework_details': 'تفاصيل الواجب',
      'grade_submission': 'تقييم المشاركة',
      'review_submissions': 'مراجعة المشاركات',
      'grade_label': 'الدرجة',
      'feedback_label': 'ملاحظات',
      'out_of': 'من أصل',
      'status_submitted': 'مُرسل',
      'status_graded': 'مُقيّم',
      'status_pending': 'قيد الانتظار',
      'personal_information': 'المعلومات الشخصية',
      'change_password_title': 'تغيير كلمة المرور',
      'current_password': 'كلمة المرور الحالية',

      // Student Role
      'student_dashboard': 'لوحة الطالب',
      'upcoming_exams': 'الاختبارات القادمة',
      'pending_homework': 'الواجبات المعلقة',
      'my_grades': 'درجاتي',
      'subject_details': 'تفاصيل المادة',
      'lesson_title': 'الدرس',
      'grades_tab': 'الدرجات',
      'lessons_tab': 'الدروس',
      'homework_tab': 'الواجبات',
      'exams_tab': 'الاختبارات',
      'gpa_tracker': 'معدلي التراكمي',
      'attendance_tracker': 'متابعة الحضور',
      'scan_qr_title': 'مسح رمز QR للحضور',
      'align_qr': 'قم بمحاذاة رمز QR داخل الإطار لمسحه',
      'enter_code_title_student': 'إدخال رمز الحضور',
      'enter_4_digit': 'أدخل الرمز المكون من 4 أرقام للجلسة',
      'attendance_success_title': 'تم تسجيل حضورك بنجاح!',
      'attendance_success_desc': 'تم تسجيل حضورك لهذه الجلسة بنجاح.',
      'attendance_absent_title': 'تم تسجيلك غائباً',
      'attendance_absent_desc':
          'يرجى التواصل مع معلمك إذا كنت تعتقد أن هذا خطأ.',

      // Parent Role
      'parent_dashboard': 'لوحة ولي الأمر',
      'my_kids': 'أبنائي',
      'child_grades': 'الدرجات والتقدم الأكاديمي',
      'child_attendance': 'حالة الحضور والغياب',
      'child_schedule': 'جدول الفصول الأسبوعي',
      'payments_header': 'الرسوم والمدفوعات',
      'payment_history': 'سجل المدفوعات',
      'secure_checkout': 'الدفع الآمن',
      'pay_now': 'ادفع الآن',
      'paid': 'مدفوع',
      'unpaid': 'غير مدفوع',
      'receipt': 'إيصال الدفع',
      'receipt_no': 'رقم الإيصال',
      'invoice_to': 'فاتورة إلى',
      'payment_method': 'طريقة الدفع',
      'transaction_id': 'معرف العملية',
      'amount': 'المبلغ',
      'total': 'الإجمالي',
      'download_pdf': 'تحميل PDF',
      'submitted': 'تم تسليمه',
      'due_date': 'تاريخ التسليم',
      'due_time': 'وقت التسليم',
      'time': 'الوقت',
      'date': 'التاريخ',
      'description': 'الوصف',
      'instructions': 'التعليمات',
      'reference_files': 'الملفات المرجعية',
      'select_class': 'اختر الفصل',
      'choose_class': 'اختر فصلاً',
      'select_subject': 'اختر المادة',
      'choose_subject': 'اختر مادة',
      'homework_title': 'عنوان الواجب',
      'homework_title_hint': 'مثال: تدريب على المعادلات التربيعية',
      'description_hint': 'أدخل وصفاً عاماً للواجب...',
      'instructions_hint': 'أدخل تعليمات أو متطلبات محددة...',
      'points_grade': 'النقاط / الدرجة القصوى',
      'attachments': 'المرفقات',
      'create_homework': 'إنشاء واجب',
      'fill_required': 'يرجى ملء جميع الحقول المطلوبة',
      'upload_pdf': 'تحميل PDF',
      'add_images': 'إضافة صور',
      'Lesson_title': 'عنوان الدرس',
      'lesson_title_hint': 'مثال: مقدمة في المعادلات التربيعية',
      'scheduled_date_time': 'التاريخ والوقت المجدول',
      'select_date_time': 'اختر التاريخ والوقت',
      'desc_objectives': 'الوصف / الأهداف',
      'learn_hint': 'ماذا سيتعلم الطلاب؟',
      'publish_lesson': 'نشر الدرس',
      'class_section': 'الصف / الفصل',
      'avg_score': 'متوسط الدرجة',
      'to_grade': 'قيد التقييم',
      'full_name': 'الاسم الكامل',
      'email_address': 'البريد الإلكتروني',
      'phone_number': 'رقم الهاتف',
      'department': 'القسم',
      'employee_id': 'الرقم الوظيفي',
      'change_password': 'تغيير كلمة المرور',
      'Current password': 'كلمة المرور الحالية',
      'New_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'enrolled': 'المسجلون',
      'marked_absent': 'المسجلون غياباً',
      'view_class': 'عرض الفصل',
      'retry': 'إعادة المحاولة',
    },
  };
}

extension LocalizationExtension on String {
  String tr() {
    return LocalizationHelper.tr(this);
  }
}
